env:
  NIX_PATH: "channel:nixos-19.03"
  BUILD_DIR: "/build/cardano-wallet"
  STACK_ROOT: "/build/cardano-wallet.stack"
  CACHE_DIR: "/cache/cardano-wallet"
  SCRATCH_DIR: "/scratch/cardano-wallet"

steps:
  - label: 'Database benchmark'
    command: "./.buildkite/bench-db.sh"
    timeout_in_minutes: 120
    agents:
      system: x86_64-linux

  - label: 'Latency benchmark'
    command: "./.buildkite/bench-latency.sh"
    timeout_in_minutes: 120
    agents:
      system: x86_64-linux

  - label: 'Database Migrations Test'
    commands:
      - "rm -rf state-migration-test*"
      - "nix-build nix/migration-tests.nix -o migration-tests"
      - "./migration-tests/runall.sh"
    timeout_in_minutes: 60
    agents:
      system: x86_64-linux

  - block: 'Delete CI Caches'

  - label: 'Clean up CI cache'
    command:
      - "nix-build .buildkite/default.nix -o sr"
      - "./sr/bin/rebuild cleanup-cache --build-dir=$BUILD_DIR --cache-dir=$CACHE_DIR"
    agents:
      system: x86_64-linux

  - label: 'Purge CI cache'
    command:
      - "nix-build .buildkite/default.nix -o sr"
      - "./sr/bin/rebuild purge-cache --build-dir=$BUILD_DIR --cache-dir=$CACHE_DIR"
    agents:
      system: x86_64-linux

  - wait

  - label: "Rebuild master branch"
    trigger: "cardano-wallet"
